apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/
  - ./base/
images:
  - name: docker.io/traefik
    digest: sha256:b588cb566045e1ebb185948a8e2456f9705cb915b5f0fb5ee698184233997817 # v3.6.2
