apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/
  - ./base/
images:
  - name: docker.io/traefik
    digest: sha256:f86a2cab1b5c649070c49f883c743dd32d8485a56e3368c5f93b9e91f1e91259 # v3.6.2
