apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik
resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - ingress-class.yaml
  - service-account.yaml
  - service.yaml
